# Generated by Django 4.1 on 2024-01-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vpn_service", "0003_rename_url_page_original_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="vpn_proxi",
        ),
    ]
