# Generated by Django 4.1 on 2024-01-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn_service", "0004_remove_page_vpn_proxi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redirection",
            name="visits",
        ),
        migrations.AddField(
            model_name="redirection",
            name="route",
            field=models.CharField(default="/", max_length=255),
            preserve_default=False,
        ),
    ]
